In [6]:
import numpy as np

In [ ]:
#HERE ARE THE COMMONLY USED NUMPY FUNCTIONS THAT DEFINE BASIC STRUCTURE AND FUNCTIONALITIES OF THE ARRAYS

In [2]:
arr1=np.array([1,2,3,4])# making a 1D array

In [7]:
arr2= np.array([[1,2,3],[4,5,6]])# maiking a 2D array

In [12]:
print(arr2)
print(arr1)

[[1 2 3]
 [4 5 6]]
[1 2 3 4]


In [17]:
arr3= np.zeros((3,4))#making 2D matrix of (3,4) of all zeroes

In [18]:
arr4=np.ones((4,4))#maing 2d matrix of (4,4) of all ones

In [19]:
arr5=np.full((4,4),5) #filling an matrix with only 5s

In [21]:
arr6= np.eye(3)#making identity matrix of (3,3)

In [27]:
arr7= np.arange(1,20,2)#putting up element starting from 1 with common difference of 2


In [28]:
arr8=np.linspace(1,2,6)#dividing the range from 1 to 2 into 6 equal parts

In [30]:
arr=np.array(([1,2,3,4,5,6],[7,8,9,10,11,12]))

In [31]:
shape=arr.shape #tells the shape of the array
dimension= arr.ndim #tells the dimension of the array
dtype=arr.dtype #tells the data type of the array
size=arr.size #tells the size of the array

In [33]:
#NOW LET'S SEE SOME MORE OPERATIONS OVER ARRAYS AND THEIR PROPERTIES

In [44]:
#CREATING MATRIX OF 3X3 OF RANDOM VALUES
ARR=np.random.randint(1,10,size=(3,3))

In [45]:
print(ARR)

[[9 3 3]
 [8 9 3]
 [4 6 6]]


In [46]:
#FANCY INDEXING TO EXTRACT EVEN NUMBERS FROM ARRAY
X=np.where(ARR%2==0)
even_nums=ARR[X]

In [47]:
print(even_nums)

[8 4 6 6]


In [7]:
#RESHAPING AN ARRAY OF ONE DIMENSION OF 9 ELEMENTS INTO AN ARRAY OF DIMENSION 3X3
arr99=np.array([1,2,3,4,5,6,7,8,9])
arr33=arr99.reshape(3,3)

In [8]:
print(arr33)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
#extracting numbers greater than 50 from an array
arr50=np.arange(80)
arr51=np.where(arr50>50)

In [53]:
print(arr51)

(array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),)


In [54]:
#changing the datatype of an array from float to integer

arrfloat=np.array([1.1,2.2,3.3])
arrint=arrfloat.astype(int)
print(arrint)
print(arrint.dtype)

[1 2 3]
int64


In [10]:
#MULTIDIMENSIONAL INDEXING
# Accessing an element
print(arr33[1, 2]) # Row index 1, Column index 2 → Output: 6

6


In [11]:
#SLICING THE ARRAY
print(arr33[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [12]:
#INDEXING IN 3D MATRIX
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [13]:
#ACCESSING ELEMENTS IN 3D 
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [14]:
#VECTORIZATION IN NUMPY

In [15]:
#NORMAL LOOPS
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = []

# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)

print(result)  # Output: [1, 4, 9, 16, 25


[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [16]:
#VECTORIZATION :Vectorization allows you to perform operations on entire arrays at once, instead of iterating over elements one by one. 
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [1 4 9 16 25]

[ 1  4  9 16 25]


In [17]:
#BROADCASTING:Broadcasting is a powerful feature of NumPy that allows you to perform operations on arrays of different shapes without creating copies.
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [18]:
#Normalizing Data Using Broadcasting
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [19]:
#SOME BUILT IN MATHEMATICAL FUNCTIONS IN NUMPY
arr=np.array([3,4,5,6,7,8])

In [20]:
arr

array([3, 4, 5, 6, 7, 8])

In [22]:
#np.mean() – Compute the mean (average) of an array.
np.mean(arr)

np.float64(5.5)

In [23]:
#np.std() – Compute the standard deviation of an array
np.std(arr)

np.float64(1.707825127659933)

In [24]:
#np.var() – Compute the variance of an array.
np.var(arr)

np.float64(2.9166666666666665)

In [25]:
#np.max gives the maximum element as output
np.max(arr)

np.int64(8)

In [26]:
#np.min() gives the minimum element
np.min(arr)

np.int64(3)

In [27]:
np.sum(arr)#gives the sum of the element

np.int64(33)

In [28]:
np.prod(arr)#gives the sum of all elements

np.int64(20160)

In [29]:
np.median(arr)#gives the median value among the elements

np.float64(5.5)

In [31]:
np.percentile(arr,50)#computes the percentile of the array

np.float64(5.5)

In [32]:
np.argmax(arr)#gives the index of maximum element

np.int64(5)